### PR TITLE
Change "Sign Up" button to "Sign In with Trello".

### PR DESCRIPTION
**Pull request by n6g7**
Feedback from English users here in London: "The 'Sign Up' annoys me cause you don't really sign-up, I wish it was 'Sign In'."
So here it is, I replaced the "Sign Up" button with "Sign In with Trello" to make it clearer what's going to happen.

### CODE REVIEW

**Comment by n6g7** [comment]
The tests fail on something unrelated to my change. :(

**Comment by nicgirault** [comment]
Merci @n6g7 . J'essaye de voir ça avant dimanche soir. Relance moi si ce n'est pas fait

**Comment by n6g7** [comment]
@nicgirault Any plan to deploy the updated version? I think it's time to destock. ;)

**Comment by nicgirault** [comment]
@n6g7 So sorry I thought it was on the app.scrumble.io and not on scrumble.io! Who the hell is going on this page by the way?

It's done now

**Comment by n6g7** [comment]
I do everytime I type `scrumble` in my browser, I guess I need to improve my suggestion list.
Thanks!

**Pull request merged**
